"""Edit

Revision ID: 424611ed536f
Revises: 061e9d0f36e6
Create Date: 2025-07-25 12:20:41.894952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424611ed536f'
down_revision: Union[str, Sequence[str], None] = '061e9d0f36e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'huh')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('huh', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
